[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
energy_meter = "Cafya3JiUuZ7Via65X8D69JZemzjd1PE2RjEDKha8EbW"

[programs.devnet]
energy_meter = "EMtr1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
